Repository pimcore/generic-data-index-bundle, pull requests merged in 2024-06, with the labels that each got.

#166 Added php 8.3 support
  .github/workflows/codeception.yaml
  .github/workflows/static-analysis.yaml
  composer.json
Labels: Task

#167 Fix input quantity value data object type OpenSearch mapping
  .github/workflows/qodana.yml
  .qodana-profile.xml
  config/services/search/data-object/field-definition-adapters.yml
  qodana.yaml
  src/SearchIndexAdapter/OpenSearch/DataObject/FieldDefinitionAdapter/InputQuantityValueAdapter.php
Labels: Bug, Pimcore:ToDo

#168 Skip data object folder indexing to avoid index not found exceptions
  src/EventSubscriber/DataObjectIndexUpdateSubscriber.php
Labels: Bug

#169 Fix hasWorkflowWithPermissions check in combination with user authentication
  src/Service/Workflow/WorkflowService.php
  src/Service/Workflow/WorkflowService/WorkflowDummyUser.php
Labels: Bug

#172 Add SearchResultIdListService
  .github/ci/files/config/services_test.yaml
  config/services/search-index-adapter/open-search.yaml
  config/services/search/search-services.yaml
  doc/04_Searching_For_Data_In_Index/README.md
  src/SearchIndexAdapter/OpenSearch/Search/FetchIdsBySearchService.php
  src/SearchIndexAdapter/OpenSearch/Search/FetchIdsService.php
  src/SearchIndexAdapter/Search/FetchIdsServiceInterface.php
  src/Service/Search/SearchService/Element/ElementSearchHelperInterface.php
  src/Service/Search/SearchService/IndexNameResolver.php
  src/Service/Search/SearchService/SearchResultIdListService.php
  src/Service/Search/SearchService/SearchResultIdListServiceInterface.php
  src/Service/Search/SearchService/Traits/SearchHelperTrait.php
  src/Service/Search/SearchService/TransformToAdapterSearchService.php
  src/Service/Search/SearchService/TransformToAdapterSearchServiceInterface.php
  tests/Functional/Search/SearchService/SearchResultIdListServiceTest.php
Labels: Improvement

#173 Respect defined sort order in SearchResultIdListService
  doc/04_Searching_For_Data_In_Index/README.md
  src/SearchIndexAdapter/OpenSearch/Search/FetchIdsService.php
  src/SearchIndexAdapter/Search/FetchIdsServiceInterface.php
  src/Service/Search/SearchService/SearchResultIdListServiceInterface.php
  tests/Functional/Search/SearchService/SearchResultIdListServiceTest.php
Labels: Improvement
