Repository pimcore/generic-data-index-bundle, pull requests merged in 2024-08, with the labels that each got.

#199 Create index if not exists while trying to reindex its mapping
  src/MessageHandler/UpdateClassMappingHandler.php
  src/Service/SearchIndex/IndexService/IndexHandler/AbstractIndexHandler.php
Labels: Bug

#200 Centralize logic for class definition reindexing
  config/services/search/index.yaml
  src/Command/DeploymentReindexCommand.php
  src/Exception/ClassDefinitionIndexUpdateFailedException.php
  src/MessageHandler/UpdateClassMappingHandler.php
  src/Service/SearchIndex/ClassDefinition/ClassDefinitionReindexService.php
  src/Service/SearchIndex/ClassDefinition/ClassDefinitionReindexServiceInterface.php
  src/Service/SearchIndex/ReindexService.php
Labels: Improvement

#198 Add classDefinitionIcon to data object indices
  config/pimcore/config.yaml
  config/services/search-index-adapter/open-search.yaml
  src/Enum/SearchIndex/FieldCategory/SystemField.php
  src/Model/Search/DataObject/SearchResult/DataObjectSearchResultItem.php
  src/SearchIndexAdapter/DataObject/IndexIconUpdateServiceInterface.php
  src/SearchIndexAdapter/OpenSearch/DataObject/IndexIconUpdateService.php
  src/Service/SearchIndex/ClassDefinition/ClassDefinitionReindexService.php
  src/Service/Serializer/Denormalizer/Search/DataObjectSearchResultDenormalizer.php
  src/Service/Serializer/Normalizer/DataObjectNormalizer.php
  tests/Functional/SearchIndex/DataObjectBasicTest.php
Labels: Improvement

#195 Extend PQL with new operators (!=, not like) and support for null/empty values
  doc/04_Searching_For_Data_In_Index/09_Pimcore_Query_Language/README.md
  src/Enum/QueryLanguage/QueryTokenType.php
  src/QueryLanguage/Pql/Lexer.php
  src/QueryLanguage/Pql/Parser.php
  src/SearchIndexAdapter/OpenSearch/QueryLanguage/PqlAdapter.php
  tests/Functional/Search/Modifier/QueryLanguage/PqlFilterTest.php
  tests/Unit/QueryLanguage/Pql/LexerTest.php
  tests/Unit/QueryLanguage/Pql/ParserTest.php
Labels: Improvement

#203 Add info about auto_create_index
  doc/02_Configuration/04_Opensearch.md
Labels: Task
