Repository pimcore/generic-data-index-bundle, pull requests merged in 2024-10, with the labels that each got.

#222 [BC] Change permission checks to `view` for `searchById`
  src/Service/Search/SearchService/AbstractSearchHelper.php
  src/Service/Search/SearchService/Asset/AssetSearchService.php
  src/Service/Search/SearchService/Asset/AssetSearchServiceInterface.php
  src/Service/Search/SearchService/DataObject/DataObjectSearchService.php
  src/Service/Search/SearchService/DataObject/DataObjectSearchServiceInterface.php
  src/Service/Search/SearchService/Document/DocumentSearchService.php
  src/Service/Search/SearchService/Document/DocumentSearchServiceInterface.php
  src/Service/Search/SearchService/Element/ElementSearchHelperInterface.php
  src/Service/Search/SearchService/Element/ElementSearchService.php
  src/Service/Search/SearchService/Element/ElementSearchServiceInterface.php
  src/Service/Search/SearchService/Element/SearchHelper.php
  src/Service/Search/SearchService/SearchHelperInterface.php
Labels: New Feature, Pimcore:ToDo, BC-BREAK

#223 [Task] Reenable roave/security
  composer.json
Labels: Task, Pimcore:ToDo

#228 [Bug] Index errors with field collection fields
  src/SearchIndexAdapter/OpenSearch/DataObject/FieldDefinitionAdapter/FieldCollectionAdapter.php
Labels: Bug

#229 [Bug] Add prefixes for class definition indexes
  src/Service/SearchIndex/GlobalIndexAliasService.php
  src/Service/SearchIndex/IndexEntityService.php
  src/Service/SearchIndex/IndexService/ElementTypeAdapter/DataObjectTypeAdapter.php
  src/Service/SearchIndex/SearchIndexConfigService.php
  src/Service/SearchIndex/SearchIndexConfigServiceInterface.php
  tests/Functional/SearchIndex/DataObjectBasicTest.php
  tests/Functional/SearchIndex/IndexQueueTest.php
  tests/Support/Helper/GenericDataIndex.php
Labels: Bug, BC-BREAK

#230 [Improvement] Add element type to the getIds method of ElementSearchResult
  src/Model/Search/Element/SearchResult/ElementSearchResult.php
  tests/Functional/Search/Modifier/Filter/DependencyFiltersTest.php
Labels: Improvement

#234 [Bug] DocumentTypeAdapter getRelatedItemsOnUpdateQuery return empty query
  src/EventSubscriber/DocumentIndexUpdateSubscriber.php
  src/Service/SearchIndex/IndexService/ElementTypeAdapter/DocumentTypeAdapter.php
Labels: Bug
