Repository pimcore/generic-data-index-bundle, pull requests merged in 2024-12, with the labels that each got.

#261 Do not overwrite default failure transport
  config/pimcore/messenger.yaml
Labels: Bug

#266 [Task] Update pimcore/pimcore to ^11.5
  composer.json
Labels: Task

#267 Add class_alias for asset field definition adapters
  src/autoload.php
Labels: Task, Bug

#270 [Task] Remove deprecations and OpenSearch class_aliases
  composer.json
  doc/01_Installation/02_Upgrade.md
  src/Attribute/OpenSearch/AsSearchModifierHandler.php
  src/DependencyInjection/PimcoreGenericDataIndexExtension.php
  src/Enum/SearchIndex/OpenSearch/AttributeType.php
  src/Enum/SearchIndex/OpenSearch/ConditionType.php
  src/Enum/SearchIndex/OpenSearch/QueryType.php
  src/Enum/SearchIndex/OpenSearch/WildcardFilterMode.php
  src/Exception/OpenSearch/SearchFailedException.php
  src/Model/DefaultSearch/Debug/SearchInformation.php
  src/Model/OpenSearch/Aggregation/Aggregation.php
  src/Model/OpenSearch/Aggregation/AggregationList.php
  src/Model/OpenSearch/Debug/SearchInformation.php
  src/Model/OpenSearch/Modifier/SearchModifierContext.php
  src/Model/OpenSearch/Modifier/SearchModifierContextInterface.php
  src/Model/OpenSearch/OpenSearchSearchInterface.php
  src/Model/OpenSearch/Query/AsSubQueryInterface.php
  src/Model/OpenSearch/Query/BoolQuery.php
  src/Model/OpenSearch/Query/DateFilter.php
  src/Model/OpenSearch/Query/Query.php
  src/Model/OpenSearch/Query/QueryInterface.php
  src/Model/OpenSearch/Query/QueryList.php
  src/Model/OpenSearch/Query/SimpleQueryStringFilter.php
  src/Model/OpenSearch/Query/TermFilter.php
  src/Model/OpenSearch/Query/TermsFilter.php
  src/Model/OpenSearch/Query/WildcardFilter.php
  src/Model/OpenSearch/Search.php
  src/Model/OpenSearch/Sort/FieldSort.php
  src/Model/OpenSearch/Sort/FieldSortList.php
  src/Model/OpenSearch/Traits/QueryObjectsToArrayTrait.php
  src/Model/OpenSearch/Traits/SimplifySingleTypesTrait.php
  src/PimcoreGenericDataIndexBundle.php
  src/SearchIndexAdapter/OpenSearch/Asset/FieldDefinitionAdapter/AbstractAdapter.php
  src/SearchIndexAdapter/OpenSearch/DataObject/FieldDefinitionAdapter/AbstractAdapter.php
  src/autoload.php
Labels: Task
