Repository pimcore/generic-data-index-bundle, pull requests merged in 2024-11, with the labels that each got.

#240 [Bug] Add missing normalize methods to containers
  src/SearchIndexAdapter/OpenSearch/DataObject/FieldDefinitionAdapter/BlockAdapter.php
  src/SearchIndexAdapter/OpenSearch/DataObject/FieldDefinitionAdapter/ClassificationStoreAdapter.php
  src/SearchIndexAdapter/OpenSearch/DataObject/FieldDefinitionAdapter/ObjectBrickAdapter.php
Labels: Bug

#242 [Bug] Wrong shortcut on generic-data-index:update:index
  src/Command/Update/IndexUpdateCommand.php
Labels: Bug

#244 [Bug] Base permissions should be false by default
  src/Permission/BasePermissions.php
  tests/Unit/Service/EventServiceTest.php
  tests/Unit/Service/Permission/PermissionServiceTest.php
Labels: Bug

#246 [Improvement] Add a new search modifier to allow filtering based on the integer values
  doc/04_Searching_For_Data_In_Index/05_Search_Modifiers/README.md
  src/Model/Search/Modifier/Filter/Basic/IntegerFilter.php
  src/SearchIndexAdapter/OpenSearch/Search/Modifier/Filter/BasicFilters.php
  tests/Functional/Search/Modifier/Filter/BasicFiltersTest.php
Labels: Improvement

#249 [Improvement] Add a new search modifier for full text search
  doc/04_Searching_For_Data_In_Index/05_Search_Modifiers/README.md
  src/Model/OpenSearch/Query/SimpleQueryStringFilter.php
  src/Model/Search/Modifier/FullTextSearch/FullTextSearch.php
  src/SearchIndexAdapter/OpenSearch/Search/Modifier/FullTextSearch/FullTextSearchHandlers.php
  tests/Functional/Search/Modifier/FullTextSearch/FullTextSearchTest.php
Labels: Improvement

#251 [Bug] Wring index name passed for data objects deletion
  src/Service/SearchIndex/IndexService/ElementTypeAdapter/DataObjectTypeAdapter.php
  tests/Functional/SearchIndex/IndexQueueTest.php
  tests/Support/Helper/GenericDataIndex.php
Labels: Bug

#253 [Bug]: Add missing element search index name prefix
  src/Service/Search/SearchService/IndexNameResolver.php
Labels: Bug

#241 [Bug]: Classes with missing internal
  src/SearchIndexAdapter/OpenSearch/DataObject/IndexIconUpdateService.php
  src/SearchIndexAdapter/OpenSearch/IndexMappingService.php
  src/SearchIndexAdapter/OpenSearch/IndexStatsService.php
  src/SearchIndexAdapter/OpenSearch/QueryLanguage/FieldNameValidator/FieldExistsValidator.php
  src/SearchIndexAdapter/OpenSearch/QueryLanguage/FieldNameValidator/LocalizedFieldValidator.php
  src/SearchIndexAdapter/OpenSearch/QueryLanguage/FieldNameValidator/RelationValidator.php
  src/SearchIndexAdapter/OpenSearch/Search/FetchIdsBySearchService.php
Labels: Bug

#257 [Task]: Set deprecated service alias only when OpenSearch is used
  src/DependencyInjection/PimcoreGenericDataIndexExtension.php
Labels: Task

#260 [Bug] Fix lexer token and workflows
  .github/workflows/php-cs-fixer.yaml
  .github/workflows/sonar.yaml
  src/QueryLanguage/Pql/Parser.php
Labels: Bug

#259 [Improvement] Default Asset Metadata should be in the index
  src/SearchIndexAdapter/DefaultSearch/Asset/PredefinedAssetMetadataProvider.php
  src/Service/SearchIndex/Asset/MetadataProviderService.php
Labels: Improvement

#262 [Task] Update static resolver
  composer.json
Labels: Task

#264 [Bug] Block adapter Normalizer
  src/SearchIndexAdapter/OpenSearch/DataObject/FieldDefinitionAdapter/BlockAdapter.php
Labels: Bug
