Repository pimcore/generic-data-index-bundle, pull requests merged in 2025-02, with the labels that each got.

#283 [Bug]: Fix missing index settings default config values
  config/pimcore/config.yaml
  config/pimcore/default_index_settings.yaml
  src/DependencyInjection/PimcoreGenericDataIndexExtension.php
Labels: Bug

#282 Update carbon
  composer.json
  src/Model/DefaultSearch/Query/DateFilter.php
  src/Model/Search/Modifier/Filter/FieldType/DateFilter.php
  src/SearchIndexAdapter/DefaultSearch/Asset/FieldDefinitionAdapter/DateAdapter.php
  tests/Unit/Service/SearchIndex/CachedSearchIndexMappingServiceTest.php
Labels: Pimcore:ToDo, Internal

#287 [Tree]: Add class ids modifier
  doc/04_Searching_For_Data_In_Index/05_Search_Modifiers/README.md
  src/Model/Search/Modifier/Filter/Tree/ClassIdsFilter.php
  src/SearchIndexAdapter/DefaultSearch/Search/Modifier/Filter/TreeFilters.php
  tests/Functional/Search/Modifier/Filter/TreeFiltersTest.php
Labels: Improvement

#290 [Modifier] Adapt modifier to filter by class names or ids
  doc/01_Installation/02_Upgrade.md
  doc/04_Searching_For_Data_In_Index/05_Search_Modifiers/README.md
  src/Enum/SearchIndex/FieldCategory/SystemField.php
  src/Model/Search/DataObject/SearchResult/DataObjectSearchResultItem.php
  src/Model/Search/Modifier/Filter/Tree/ClassIdsFilter.php
  src/SearchIndexAdapter/DefaultSearch/Search/Modifier/Filter/TreeFilters.php
  src/Service/Serializer/Denormalizer/Search/DataObjectSearchResultDenormalizer.php
  src/Service/Serializer/Normalizer/DataObjectNormalizer.php
Labels: Task

#291 [Task] Add container extension
  src/PimcoreGenericDataIndexBundle.php
Labels: Task, Pimcore:ToDo
