Repository pimcore/generic-data-index-bundle, pull requests merged in 2025-03, with the labels that each got.

#295 [Improvement]: Add support to DBAL v4
  composer.json
  src/Repository/IndexQueueRepository.php
  src/Service/SearchIndex/IndexQueue/EnqueueService.php
  src/Service/SearchIndex/IndexService/ElementTypeAdapter/AssetTypeAdapter.php
  src/Service/SearchIndex/IndexService/ElementTypeAdapter/DataObjectTypeAdapter.php
  src/Service/SearchIndex/IndexService/ElementTypeAdapter/DocumentTypeAdapter.php
  tests/Functional/SearchIndex/IndexQueueTest.php
  tests/Support/Helper/Index.php
Labels: Pimcore:Priority, Improvement

#298 [Fix][Queue]: Data object folders are not indexed in async mode
  src/Service/SearchIndex/IndexService/ElementTypeAdapter/DataObjectTypeAdapter.php
  tests/Functional/SearchIndex/AssetBasicTest.php
  tests/Functional/SearchIndex/DataObjectBasicTest.php
  tests/Functional/SearchIndex/DocumentBasicTest.php
  tests/Functional/SearchIndex/IndexQueueTest.php
  tests/Support/Helper/GenericDataIndex.php
Labels: Bug

#300 [Docs] Add date-math example
  doc/04_Searching_For_Data_In_Index/09_Pimcore_Query_Language/README.md
Labels: Task

#305 [Fix]: Add missing check to enqueue data object for deletion
  src/Service/SearchIndex/IndexService/ElementTypeAdapter/DataObjectTypeAdapter.php
Labels: Bug
