Repository pimcore/generic-data-index-bundle, pull requests merged in 2025-01, with the labels that each got.

#273 [Bug] Add missing type in normalize method of object brick adapter
  src/SearchIndexAdapter/DefaultSearch/DataObject/FieldDefinitionAdapter/ObjectBrickAdapter.php
Labels: Bug

#263 Removed local sonar files
  .github/workflows/sonar.yaml
  sonar-project.properties
Labels: Pimcore:ToDo

#275 [Improvement]: Add properties for tree sorting to data object indexes
  config/pimcore/config.yaml
  src/Enum/SearchIndex/FieldCategory/SystemField.php
  src/Model/Search/DataObject/SearchResult/DataObjectSearchResultItem.php
  src/Service/Serializer/Denormalizer/Search/DataObjectSearchResultDenormalizer.php
  src/Service/Serializer/Normalizer/DataObjectNormalizer.php
Labels: Improvement

#277 Fix: sorting of the codeception results
  tests/Functional/Search/Modifier/FullTextSearch/FullTextSearchTest.php
Labels: Bug

#279 [Fix]: Add root node permissions
  .github/workflows/elastic-search-codeception.yaml
  .github/workflows/open-search-codeception.yaml
  .github/workflows/static-analysis.yaml
  src/Service/Permission/PermissionService.php
  tests/Unit/Service/Permission/PermissionServiceTest.php
Labels: Bug

#280 [Improvement]Handle special language workspace permissions
  doc/01_Installation/02_Upgrade.md
  src/Permission/DataObjectPermissions.php
  src/Permission/Workspace/AbstractWorkspace.php
  src/Permission/Workspace/WorkspaceInterface.php
  src/Service/Permission/ElementPermissionService.php
  src/Service/Permission/ElementPermissionServiceInterface.php
  src/Service/Permission/PermissionService.php
  src/Service/Permission/PermissionServiceInterface.php
  tests/Unit/Service/Permission/PermissionServiceTest.php
Labels: Improvement

#281 update docs
  doc/02_Configuration/03_Index_Management.md
Labels: Task
