Repository pimcore/generic-data-index-bundle, pull requests merged in 2025-04, with the labels that each got.

#312 [Permissions] Check if user permissions are empty
  src/Service/Permission/PermissionService.php
Labels: Bug

#313 [Elements] Add new service to return if element is locked
  config/pimcore/config.yaml
  config/services/search-index-adapter/default-search.yaml
  doc/01_Installation/02_Upgrade.md
  src/Enum/SearchIndex/DefaultSearch/QueryType.php
  src/Enum/SearchIndex/FieldCategory/SystemField.php
  src/EventSubscriber/LockElementSubscriber.php
  src/Model/Search/Asset/SearchResult/AssetSearchResultItem.php
  src/Model/Search/DataObject/SearchResult/DataObjectSearchResultItem.php
  src/Model/Search/Document/SearchResult/DocumentSearchResultItem.php
  src/Model/Search/Interfaces/ElementSearchResultItemInterface.php
  src/SearchIndexAdapter/DefaultSearch/ElementLockService.php
  src/SearchIndexAdapter/ElementLockServiceInterface.php
  src/Service/Serializer/Denormalizer/Search/AssetSearchResultDenormalizer.php
  src/Service/Serializer/Denormalizer/Search/DataObjectSearchResultDenormalizer.php
  src/Service/Serializer/Denormalizer/Search/DocumentSearchResultDenormalizer.php
  src/Service/Serializer/Normalizer/AssetNormalizer.php
  src/Service/Serializer/Normalizer/DataObjectNormalizer.php
  src/Service/Serializer/Normalizer/DocumentNormalizer.php
  tests/Functional/ElementLockServiceTest.php
  tests/bin/docker-compose.yaml
Labels: New Feature

#317 Add Product Registration
  .github/ci/files/config/packages/test/config.yaml
  .github/workflows/elastic-search-codeception.yaml
  .github/workflows/open-search-codeception.yaml
Labels: Task

#318 [Docs] Adapted Upgrade Notes
  doc/01_Installation/02_Upgrade.md
Labels: Task

#321 [Task] Add missing information about changed prefix
  doc/01_Installation/02_Upgrade.md
Labels: Task
